- .eslintignore
- package.json
- samples/package.json
- samples/quickstart.js
- samples/recognize.js
- samples/system-test/quickstart.test.js
- samples/system-test/recognize.test.js
- src/helpers.js
- src/index.js
- src/v1/index.js
- src/v1/speech_client.js
- system-test/.eslintrc.yml
- test/gapic-v1.test.js
- test/helpers.test.js
This gets the branch into compliance with ESLint.
> Lint all the things

- package.json
- samples/package.json
Release notes are staged in the GitHub releases area.
> Bump version to 0.11.0

- .circleci/config.yml
- .cloud-repo-tools.json
- CONTRIBUTORS
- README.md
- package.json
- samples/package.json
- CI to be run as non-privileged user to save time
- Bumping version to 1.0.0. Ready for ~~takeoff~~ GA!
> release 1.0.0 for GA

- package-lock.json
- protos/google/cloud/speech/v1p1beta1/cloud_speech.proto
- samples/package-lock.json
- src/v1p1beta1/doc/google/cloud/speech/v1p1beta1/doc_cloud_speech.js
- src/v1p1beta1/speech_client.js
- test/gapic-v1p1beta1.js
Just a regular GAPIC code update as requested by API owners.
> regenerate GAPIC v1p1beta1 generated code

- samples/recognize.v1p1beta1.js
- samples/system-test/recognize.v1p1beta1.test.js
> Added metadata sample code

- protos/google/cloud/speech/v1p1beta1/cloud_speech.proto
- smoke-test/speech_smoke_test.js
- src/v1p1beta1/doc/google/cloud/speech/v1p1beta1/doc_cloud_speech.js
- test/gapic-v1p1beta1.js
> Regenerate speech v1p1beta1

- samples/recognize.v1p1beta1.js
Alex and Rebecca suggested to add some comments for the developers to be aware of possible future changes in the library. This PR is to add those comments.
> Added the TODO comment suggested by Alex & Rebecca

- .appveyor.yml
> chore: add Node.js 10

- .gitignore
- protos/google/cloud/speech/v1beta1/cloud_speech.proto
- smoke-test/speech_smoke_test.js
- src/index.js
- src/v1beta1/doc/google/cloud/speech/v1beta1/doc_cloud_speech.js
- src/v1beta1/doc/google/longrunning/doc_operations.js
- src/v1beta1/doc/google/protobuf/doc_any.js
- src/v1beta1/doc/google/rpc/doc_status.js
- src/v1beta1/index.js
- src/v1beta1/speech_client.js
- src/v1beta1/speech_client_config.json
- synth.py
- test/gapic-v1beta1.js
> Add v1beta1 version

- .circleci/config.yml
fixes failing lint in circleci
> fix: npm link ../ before npm install in samples

- .circleci/config.yml
- src/helpers.js
- synth.py
- test/gapic-v1.js
- test/gapic-v1p1beta1.js
- test/helpers.test.js
Fixes https://github.com/googleapis/gapic-generator/issues/2129 . Originally this was thought to be an issue with the generated test but our helper had behavior that caused failures with the tests.
> modify helpers.js to be compatible with generated code

- samples/system-test/betaFeatures.test.js
> fix: use regex to test output

- .kokoro/common.cfg
- .kokoro/docs.sh
- .kokoro/lint.sh
- .kokoro/samples-test.sh
- .kokoro/system-test.sh
- .kokoro/test.bat
- .kokoro/test.sh
- .kokoro/trampoline.sh
This PR was created by autosynth.
> Re-generate library using None/synth.py

- CHANGELOG.md
- package.json
- samples/package.json
This pull request was generated using releasetool.
Resolves #194
> Release @google-cloud/speech v2.1.1

- samples/recognize.js
> fix typo in sample

- CHANGELOG.md
- package.json
- samples/package.json
This pull request was generated using releasetool.
> Release @google-cloud/speech v2.1.2

- CHANGELOG.md
- package.json
- samples/package.json
This pull request was generated using releasetool.
> Release @google-cloud/speech v2.2.0

- CHANGELOG.md
- package.json
- samples/package.json
This pull request was generated using releasetool.
> Release @google-cloud/speech v2.3.1

- samples/infiniteStreaming.js
> Increase timeout to 5 mins

- samples/infiniteStreaming.js
> docs(samples): fix infinite streaming example typo

- samples/MicrophoneStream.js
- samples/infiniteStreaming.js
- samples/package.json
- samples/recognize.js
> fix(samples) : speech streaming update dependency of node-record-lpcm16

- samples/system-test/betaFeatures.test.js
> test: switch tests to new resource names

- samples/infiniteStreaming.js
Staging samples for review within tutorial.
> refactored and added tags to infinite speech streaming sample

- samples/system-test/transcribeContextClasses.test.js
- samples/transcribeContextClasses.js
Creates a sample showing Speech Contexts with the speech API.  
http://b/148626322
> feat: created sample for speechcontext classes

- protos/protos.js
- src/v1/speech_client.ts
- src/v1p1beta1/speech_client.ts
- synth.metadata
- test/gapic_speech_v1.ts
- test/gapic_speech_v1p1beta1.ts
For each client method returning a long running operation, a separate method to check its status is added.
Added methods: `checkLongRunningRecognizeProgress`.
> feat: check status of long running operation by its name

- samples/infiniteStreaming.js
> fix(samples): use writable stream
